import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {FaSun} from 'react-icons/fa'
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import Image from 'next/image'
import earth from '../public/earth3.png'
import tools from '../public/tools.png'
import genesys from '../public/genesys-logo.png'
import {useState} from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  let darkModeIcon;

  if (darkMode) {
    darkModeIcon = <FaSun onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl' color='white'/>
  } else {
    darkModeIcon = <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/>
  }

  return (
    <div className={darkMode ? "dark" : ""}>
      <div className='bg-white dark:bg-gray-900'>
        <Head>
          <title>Dustin Beckett Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className='bg-white px-10 md:w-9/12 lg:w-9/12 mx-auto dark:bg-gray-900'>
          <section className='min-h-full'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl text-black dark:text-white'>developedbydustin</h1> 
            <ul className='flex items-center'>
              <li>
                {darkModeIcon}
              </li>
              <li>
                <a 
                  className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8'
                  href='#'
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>
              Dustin Beckett
            </h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Software Engineer</h3>
            <p className='text-2xl py-5 leading-8 text-gray-800 mx-auto dark:text-gray-400'>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
              Ultrices gravida dictum fusce ut. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. 
              Consectetur a erat nam at lectus. Mi ipsum faucibus vitae aliquet.
            </p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-200'>
            <AiFillLinkedin />
            <AiFillGithub />
          </div>

          {/* <div className='relative mx-auto bg-gradient-to-b rounded-full w-80 h-80 mt-20'>
            <Image  src={earth} />
          </div> */}
          </section>
          {/* 2nd page */}

          <section>
            <div>
              <h3 className='text-3xl py-1 dark:text-white'>Experience</h3>
              <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Ultrices gravida dictum fusce ut. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. 
                Consectetur a erat nam at lectus. Mi ipsum faucibus vitae aliquet.
              </p>

              <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Ultrices gravida dictum fusce ut. <span className='text-teal-500'> Sit amet </span> volutpat consequat mauris nunc congue nisi vitae suscipit. 
                Consectetur a erat nam at lectus. Mi ipsum <span className='text-teal-500'> Sit amet </span> faucibus vitae aliquet.
              </p>
            </div>

            {/* Cards */}
            <div className='grid grid-cols-2 gap-x-10 gap-y-0 '>

              <div className='col-span-2 text-center shadow-xl p-10 rounded-xl my-10 dark:bg-gray-800'>
                <Image src={genesys} width={150} height={150} className='inline'/>
                <h3 className='text-lg font-medium pb-2 dark:text-white'>Genesys</h3>
                <p className='pb-2 dark:text-white'>
                 2020-Present 
                </p>
                <h4 className='py-4 text-teal-600'>Software Engineer</h4>
                <ul className='list-disc text-left px-4'>
                  <li className='text-gray-800 py-1 dark:text-gray-400'>something about being on call</li>
                  <li className='text-gray-800 py-1 dark:text-gray-400'>something about working on the out limits clients (caching, maintaining) </li>
                  <li className='text-gray-800 py-1 dark:text-gray-400'>Primary reviewer on pull requests </li>
                  <li className='text-gray-800 py-1 dark:text-gray-400'>migrated old apis to our public api platform</li>
                </ul>
              </div>

              <div className='col-span-2  text-center shadow-xl p-10 rounded-xl my-10 dark:bg-gray-800'>
                <Image src={genesys} width={150} height={150} className='inline'/>
                <h3 className='text-lg font-medium pb-2 dark:text-white'>Genesys (Internship)</h3>
                <p className='pb-2 dark:text-white'>
                 2019-2020 
                </p>
                <h4 className='py-4 text-teal-600'>Software Engineer Intern</h4>
                <ul className='list-disc text-left px-4'>
                  <li className='text-gray-800 py-1 dark:text-gray-400'>Improved the Public APIs property management system by creating a class that handled retrieving properties from local YAML files and an Amazon DynamoDB instance</li>
                  <li className='text-gray-800 py-1 dark:text-gray-400'>Explored new ways to automate version bumping using Jenkins and Grunt when making commits to a projects master branch </li>
                  <li className='text-gray-800 py-1 dark:text-gray-400'>Developed my skills in a DevOps work environment by working on tickets and automating tasks such as building, testing, and deploying software</li>
                  <li className='text-gray-800 py-1 dark:text-gray-400'>Developed additions to software that had a codebase of over half a million lines of code </li>
                  <li className='text-gray-800 py-1 dark:text-gray-400'>Utilized many tools such as Maven, Git, IntelliJ IDEA, and Jenkins to simplify and reduce the amount of time taken during the development process </li>
                  <li className='text-gray-800 py-1 dark:text-gray-400'>Established CheckStyle rules for the Public API repository to enforce specific coding standards to improve maintainability </li>
                </ul>
              </div>

              <div className='col-span-2 md:col-span-1 grow text-center shadow-xl p-10 rounded-xl my-10 dark:bg-gray-800'>
                <Image src={tools} width={100} height={100} className='inline'/>
                <h3 className='text-lg font-medium pb-2 dark:text-white'>Tools</h3>
                <p className='pb-2 dark:text-white'>
                  Tools I am proficient with.
                </p>
                <h4 className='py-4 text-teal-600'>Development tools I use</h4>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Git</p>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Jenkins</p>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Maven</p>
              </div>

              <div className='col-span-2 md:col-span-1 grow text-center shadow-xl p-10 rounded-xl my-10 dark:bg-gray-800'>
                <Image src={tools} width={100} height={100} className='inline'/>
                <h3 className='text-lg font-medium pb-2 dark:text-white'>Programming Languages</h3>
                <h4 className='py-4 text-teal-600'>Programming languages I use</h4>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Java</p>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Python</p>
              </div>

            </div> 
            { /* End of Cards */}
          </section>
          <section>
            <div>
              <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
              <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Ultrices gravida dictum fusce ut. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. 
                Consectetur a erat nam at lectus. Mi ipsum faucibus vitae aliquet.
              </p>

              <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Ultrices gravida dictum fusce ut. <span className='text-teal-500'> Sit amet </span> volutpat consequat mauris nunc congue nisi vitae suscipit. 
                Consectetur a erat nam at lectus. Mi ipsum <span className='text-teal-500'> Sit amet </span> faucibus vitae aliquet.
              </p>
            </div>
            <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
              <div className='basis-1/3 flex-1'><Image src={earth} width={'100%'} height={'100%'} className='rounded-lg object-cover' layout='responsive'/></div>
              <div className='basis-1/3 flex-1'><Image src={earth} width={'100%'} height={'100%'} className='rounded-lg object-cover' layout='responsive'/></div>
              <div className='basis-1/3 flex-1'><Image src={earth} width={'100%'} height={'100%'} className='rounded-lg object-cover' layout='responsive'/></div>
              <div className='basis-1/3 flex-1'><Image src={earth} width={'100%'} height={'100%'} className='rounded-lg object-cover' layout='responsive'/></div>
              <div className='basis-1/3 flex-1'><Image src={earth} width={'100%'} height={'100%'} className='rounded-lg object-cover' layout='responsive'/></div>
              <div className='basis-1/3 flex-1'><Image src={earth} width={'100%'} height={'100%'} className='rounded-lg object-cover' layout='responsive'/></div>
            </div>
          </section>
        </main>
      </div>
    </div>
  )
}
