import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import Image from 'next/image'
import earth from '../public/earth3.png'
import tools from '../public/tools.png'
import code from '../public/earth2.jpg'
import {useState} from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Dustin Beckett Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:w-9/12 lg:w-9/12 mx-auto dark:bg-gray-900'>
        <section className='min-h-full'>
         <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl'>developedbydustin</h1> 
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/>
            </li>
            <li>
              <a 
                className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8'
                href='#'
              >
                Resume
              </a>
             </li>
          </ul>
         </nav>
         
         <div className='text-center p-10'>
          <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>
            Dustin Beckett
          </h2>
          <h3 className='text-2xl py-2 md:text-3xl'>Software Engineer</h3>
          <p className='text-2xl py-5 leading-8 text-gray-800 mx-auto'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            Ultrices gravida dictum fusce ut. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. 
            Consectetur a erat nam at lectus. Mi ipsum faucibus vitae aliquet.
          </p>
         </div>

         <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
          <AiFillLinkedin />
          <AiFillGithub />
         </div>

         {/* <div className='relative mx-auto bg-gradient-to-b rounded-full w-80 h-80 mt-20'>
          <Image  src={earth} />
         </div> */}
        </section>
        {/* 2nd page */}

        <section>
          <div>
            <h3 className='text-3xl py-1'>Experience</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
              Ultrices gravida dictum fusce ut. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. 
              Consectetur a erat nam at lectus. Mi ipsum faucibus vitae aliquet.
            </p>

            <p className='text-md py-2 leading-8 text-gray-800'>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
              Ultrices gravida dictum fusce ut. <span className='text-teal-500'> Sit amet </span> volutpat consequat mauris nunc congue nisi vitae suscipit. 
              Consectetur a erat nam at lectus. Mi ipsum <span className='text-teal-500'> Sit amet </span> faucibus vitae aliquet.
            </p>
          </div>

          {/* Cards */}
          <div className='lg:flex gap-10 mx-auto'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={tools} width={100} height={100} className='inline'/>
              <h3 className='text-lg font-medium pb-2'>Tools</h3>
              <p className='pb-2'>
                Tools I am proficient with.
              </p>
              <h4 className='py-4 text-teal-600'>Development tools I use</h4>
              <p className='text-gray-800 py-1'>Docker</p>
              <p className='text-gray-800 py-1'>Jenkins</p>
              <p className='text-gray-800 py-1'>Vim</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={tools} width={100} height={100} className='inline'/>
              <h3 className='text-lg font-medium pb-2'>Tools</h3>
              <p className='pb-2'>
                Tools I am proficient with.
              </p>
              <h4 className='py-4 text-teal-600'>Development tools I use</h4>
              <p className='text-gray-800 py-1'>Docker</p>
              <p className='text-gray-800 py-1'>Jenkins</p>
              <p className='text-gray-800 py-1'>Vim</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={tools} width={100} height={100} className='inline'/>
              <h3 className='text-lg font-medium pb-2'>Tools</h3>
              <p className='pb-2'>
                Tools I am proficient with.
              </p>
              <h4 className='py-4 text-teal-600'>Development tools I use</h4>
              <p className='text-gray-800 py-1'>Docker</p>
              <p className='text-gray-800 py-1'>Jenkins</p>
              <p className='text-gray-800 py-1'>Vim</p>
            </div>
          </div> 
          { /* End of Cards */}
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
              Ultrices gravida dictum fusce ut. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. 
              Consectetur a erat nam at lectus. Mi ipsum faucibus vitae aliquet.
            </p>

            <p className='text-md py-2 leading-8 text-gray-800'>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
              Ultrices gravida dictum fusce ut. <span className='text-teal-500'> Sit amet </span> volutpat consequat mauris nunc congue nisi vitae suscipit. 
              Consectetur a erat nam at lectus. Mi ipsum <span className='text-teal-500'> Sit amet </span> faucibus vitae aliquet.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'><Image src={earth} width={'100%'} height={'100%'} className='rounded-lg object-cover' layout='responsive'/></div>
            <div className='basis-1/3 flex-1'><Image src={earth} width={'100%'} height={'100%'} className='rounded-lg object-cover' layout='responsive'/></div>
            <div className='basis-1/3 flex-1'><Image src={earth} width={'100%'} height={'100%'} className='rounded-lg object-cover' layout='responsive'/></div>
            <div className='basis-1/3 flex-1'><Image src={earth} width={'100%'} height={'100%'} className='rounded-lg object-cover' layout='responsive'/></div>
            <div className='basis-1/3 flex-1'><Image src={earth} width={'100%'} height={'100%'} className='rounded-lg object-cover' layout='responsive'/></div>
            <div className='basis-1/3 flex-1'><Image src={earth} width={'100%'} height={'100%'} className='rounded-lg object-cover' layout='responsive'/></div>
          </div>
        </section>
      </main>
    </div>
  )
}
